### ISSUE TITLE
cant

### ISSUE THREAD

**Issue by Proofr** [rimmvb/eaglercrack#1]
i found a noob named rimm in the client pls help i think i have virus

**Comment by eaglercrack** [comment]
anybody here to help?

**Comment by rimmvb** [comment]
nope

**Comment by eaglercrack** [comment]
please somebody help i think im getting hacked the noob commented again

**Comment by Proofr** [comment]
am i the only one seeing a rimmvb talking pls help

**Comment by eaglercrack** [comment]
agggrred

**Comment by rimmvb** [comment]
keep yappin man

**Comment by eaglercrack** [comment]
duck you haha see what i did there

**Comment by Proofr** [comment]
fancy like

**Comment by rimmvb** [comment]
@Proofr @ProofrTemp ### 

1. #1. > [`_****_`](url)

**Comment by Proofr** [comment]
applebeees is fancy like dennys

**Comment by Proofr** [comment]
pls!?

**Comment by STPv22** [comment]
Applebees and Denny's syrup goes hard

**Comment by player-k12** [comment]
most normal conversation on github
