### ISSUE TITLE
Wasn't sure where to put this...

### ISSUE THREAD

**Issue by STPv22** [rimmvb/eaglercrack#5]
With 1.8 singleplayer out, i was wondering if you could add a "maps" page? I'm making a PvP map myself, and it would be great to put it on here.

**Comment by rimmvb** [comment]
This idea was added its in the navbar under "Worlds" Feel free to create a pull request or send the epk in the worlds channel in our discord

**Comment by STPv22** [comment]
I don't have discord, could I make a pull request insead?
